export interface DriverOrder {
  id: number;
  order_app: string;
  table_number: string;
  date: string | null;
  restaurant_id: number;
  status: string;
  delivery_status: "accepted" | "picked_up" | "on_route" | "arrived" | "delivered" | "failed";
  delivery_photo: string | null;
  delivery_signature: string | null;
  delivery_otp: string | null;
  is_otp_verified: number;
  delivery_notes: string | null;
  delivery_failure_reason: string | null;
  delivery_failure_description: string | null;
  payment_status: string;
  total_due_amount: string;
  amount: string;
  tip_amount: string;
  final_price: string;
  discount: string;
  discount_type: string;
  tax: string;
  payment_method: string | null;
  remarks: string | null;
  type: string;
  autoprint: string;
  customer_name: string;
  customer_phone: string;
  customer_post_code: string;
  customer_address: string;
  latitude: string | null;
  longitude: string | null;
  order_by: number;
  customer_id: number;
  driver_id: number;
  waiter_id: number | null;
  cash: string;
  card: string;
  request_object: unknown | null;
  initial_note: string | null;
  customer_note: string | null;
  coupon_type: string | null;
  coupon_amount: string | null;
  created_at: string;
  updated_at: string;
  order_time: string | null;
  door_no: string;
  payment_intent_id: string | null;
  accepted_at: string | null;
  picked_up_at: string | null;
  delivered_at: string | null;
}
