export const currencyOptions = [
  {
    id: 1,
    value: "AED",
    name: "AED",
    title: "United Arab Emirates dirham",
    symbol: "د.إ",
    label: "د.إ",
  },
  {
    id: 2,
    value: "AFN",
    name: "AFN",
    title: "Afghan afghani",
    symbol: "؋",
    label: "؋",
  },
  {
    id: 3,
    value: "ALL",
    name: "ALL",
    title: "Albanian lek",
    symbol: "L",
    label: "L",
  },
  {
    id: 4,
    value: "AMD",
    name: "AMD",
    title: "Armenian dram",
    symbol: "֏",
    label: "֏",
  },
  {
    id: 5,
    value: "ANG",
    name: "ANG",
    title: "Netherlands Antillean guilder",
    symbol: "ƒ",
    label: "ƒ",
  },
  {
    id: 6,
    value: "AOA",
    name: "AOA",
    title: "Angolan kwanza",
    symbol: "Kz",
    label: "Kz",
  },
  {
    id: 7,
    value: "ARS",
    name: "ARS",
    title: "Argentine peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 8,
    value: "AUD",
    name: "AUD",
    title: "Australian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 9,
    value: "AWG",
    name: "AWG",
    title: "Aruban florin",
    symbol: "ƒ",
    label: "ƒ",
  },
  {
    id: 10,
    value: "AZN",
    name: "AZN",
    title: "Azerbaijani manat",
    symbol: "₼",
    label: "₼",
  },
  {
    id: 11,
    value: "BAM",
    name: "BAM",
    title: "Bosnia and Herzegovina convertible mark",
    symbol: "KM",
    label: "KM",
  },
  {
    id: 12,
    value: "BBD",
    name: "BBD",
    title: "Barbadian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 13,
    value: "BDT",
    name: "BDT",
    title: "Bangladeshi taka",
    symbol: "৳",
    label: "৳",
  },
  {
    id: 14,
    value: "BGN",
    name: "BGN",
    title: "Bulgarian lev",
    symbol: "лв",
    label: "лв",
  },
  {
    id: 15,
    value: "BHD",
    name: "BHD",
    title: "Bahraini dinar",
    symbol: ".د.ب",
    label: ".د.ب",
  },
  {
    id: 16,
    value: "BIF",
    name: "BIF",
    title: "Burundian franc",
    symbol: "FBu",
    label: "FBu",
  },
  {
    id: 17,
    value: "BMD",
    name: "BMD",
    title: "Bermudian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 18,
    value: "BND",
    name: "BND",
    title: "Brunei dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 19,
    value: "BOB",
    name: "BOB",
    title: "Bolivian boliviano",
    symbol: "Bs.",
    label: "Bs.",
  },
  {
    id: 20,
    value: "BRL",
    name: "BRL",
    title: "Brazilian real",
    symbol: "R$",
    label: "R$",
  },
  {
    id: 21,
    value: "BSD",
    name: "BSD",
    title: "Bahamian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 22,
    value: "BTN",
    name: "BTN",
    title: "Bhutanese ngultrum",
    symbol: "Nu.",
    label: "Nu.",
  },
  {
    id: 23,
    value: "BWP",
    name: "BWP",
    title: "Botswana pula",
    symbol: "P",
    label: "P",
  },
  {
    id: 24,
    value: "BYN",
    name: "BYN",
    title: "Belarusian ruble",
    symbol: "Br",
    label: "Br",
  },
  {
    id: 25,
    value: "BZD",
    name: "BZD",
    title: "Belize dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 26,
    value: "CAD",
    name: "CAD",
    title: "Canadian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 27,
    value: "CDF",
    name: "CDF",
    title: "Congolese franc",
    symbol: "FC",
    label: "FC",
  },
  {
    id: 28,
    value: "CHF",
    name: "CHF",
    title: "Swiss franc",
    symbol: "Fr.",
    label: "Fr.",
  },
  {
    id: 29,
    value: "CLP",
    name: "CLP",
    title: "Chilean peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 30,
    value: "CNY",
    name: "CNY",
    title: "Chinese yuan",
    symbol: "¥",
    label: "¥",
  },
  {
    id: 31,
    value: "COP",
    name: "COP",
    title: "Colombian peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 32,
    value: "CRC",
    name: "CRC",
    title: "Costa Rican colón",
    symbol: "₡",
    label: "₡",
  },
  {
    id: 33,
    value: "CUP",
    name: "CUP",
    title: "Cuban peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 34,
    value: "CVE",
    name: "CVE",
    title: "Cape Verdean escudo",
    symbol: "$",
    label: "$",
  },
  {
    id: 35,
    value: "CZK",
    name: "CZK",
    title: "Czech koruna",
    symbol: "Kč",
    label: "Kč",
  },
  {
    id: 36,
    value: "DJF",
    name: "DJF",
    title: "Djiboutian franc",
    symbol: "Fdj",
    label: "Fdj",
  },
  {
    id: 37,
    value: "DKK",
    name: "DKK",
    title: "Danish krone",
    symbol: "kr",
    label: "kr",
  },
  {
    id: 38,
    value: "DOP",
    name: "DOP",
    title: "Dominican peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 39,
    value: "DZD",
    name: "DZD",
    title: "Algerian dinar",
    symbol: "د.ج",
    label: "د.ج",
  },
  {
    id: 40,
    value: "EGP",
    name: "EGP",
    title: "Egyptian pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 41,
    value: "ERN",
    name: "ERN",
    title: "Eritrean nakfa",
    symbol: "Nfk",
    label: "Nfk",
  },
  {
    id: 42,
    value: "ETB",
    name: "ETB",
    title: "Ethiopian birr",
    symbol: "Br",
    label: "Br",
  },
  { id: 43, value: "EUR", name: "EUR", title: "Euro", symbol: "€", label: "€" },
  {
    id: 44,
    value: "FJD",
    name: "FJD",
    title: "Fijian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 45,
    value: "FKP",
    name: "FKP",
    title: "Falkland Islands pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 46,
    value: "FOK",
    name: "FOK",
    title: "Faroese króna",
    symbol: "kr",
    label: "kr",
  },
  {
    id: 47,
    value: "FRT",
    name: "FRT",
    title: "Forint",
    symbol: "Ft",
    label: "Ft",
  },
  {
    id: 48,
    value: "GEL",
    name: "GEL",
    title: "Georgian lari",
    symbol: "₾",
    label: "₾",
  },
  {
    id: 49,
    value: "GGP",
    name: "GGP",
    title: "Guernsey pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 50,
    value: "GHS",
    name: "GHS",
    title: "Ghanaian cedi",
    symbol: "₵",
    label: "₵",
  },
  {
    id: 51,
    value: "GIP",
    name: "GIP",
    title: "Gibraltar pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 52,
    value: "GMD",
    name: "GMD",
    title: "Gambian dalasi",
    symbol: "D",
    label: "D",
  },
  {
    id: 53,
    value: "GNF",
    name: "GNF",
    title: "Guinean franc",
    symbol: "FG",
    label: "FG",
  },
  {
    id: 54,
    value: "GTQ",
    name: "GTQ",
    title: "Guatemalan quetzal",
    symbol: "Q",
    label: "Q",
  },
  {
    id: 55,
    value: "GYD",
    name: "GYD",
    title: "Guyanese dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 56,
    value: "HKD",
    name: "HKD",
    title: "Hong Kong dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 57,
    value: "HNL",
    name: "HNL",
    title: "Honduran lempira",
    symbol: "L",
    label: "L",
  },
  {
    id: 58,
    value: "HRK",
    name: "HRK",
    title: "Croatian kuna",
    symbol: "kn",
    label: "kn",
  },
  {
    id: 59,
    value: "HTG",
    name: "HTG",
    title: "Haitian gourde",
    symbol: "G",
    label: "G",
  },
  {
    id: 60,
    value: "HUF",
    name: "HUF",
    title: "Hungarian forint",
    symbol: "Ft",
    label: "Ft",
  },
  {
    id: 61,
    value: "IDR",
    name: "IDR",
    title: "Indonesian rupiah",
    symbol: "Rp",
    label: "Rp",
  },
  {
    id: 62,
    value: "ILS",
    name: "ILS",
    title: "Israeli new shekel",
    symbol: "₪",
    label: "₪",
  },
  {
    id: 63,
    value: "IMP",
    name: "IMP",
    title: "Isle of Man pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 64,
    value: "INR",
    name: "INR",
    title: "Indian rupee",
    symbol: "₹",
    label: "₹",
  },
  {
    id: 65,
    value: "IQD",
    name: "IQD",
    title: "Iraqi dinar",
    symbol: "ع.د",
    label: "ع.د",
  },
  {
    id: 66,
    value: "IRR",
    name: "IRR",
    title: "Iranian rial",
    symbol: "﷼",
    label: "﷼",
  },
  {
    id: 67,
    value: "ISK",
    name: "ISK",
    title: "Icelandic króna",
    symbol: "kr",
    label: "kr",
  },
  {
    id: 68,
    value: "JEP",
    name: "JEP",
    title: "Jersey pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 69,
    value: "JMD",
    name: "JMD",
    title: "Jamaican dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 70,
    value: "JOD",
    name: "JOD",
    title: "Jordanian dinar",
    symbol: "د.ا",
    label: "د.ا",
  },
  {
    id: 71,
    value: "JPY",
    name: "JPY",
    title: "Japanese yen",
    symbol: "¥",
    label: "¥",
  },
  {
    id: 72,
    value: "KES",
    name: "KES",
    title: "Kenyan shilling",
    symbol: "Sh",
    label: "Sh",
  },
  {
    id: 73,
    value: "KGS",
    name: "KGS",
    title: "Kyrgyzstani som",
    symbol: "лв",
    label: "лв",
  },
  {
    id: 74,
    value: "KHR",
    name: "KHR",
    title: "Cambodian riel",
    symbol: "៛",
    label: "៛",
  },
  {
    id: 75,
    value: "KID",
    name: "KID",
    title: "Kiribati dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 76,
    value: "KMF",
    name: "KMF",
    title: "Comorian franc",
    symbol: "CF",
    label: "CF",
  },
  {
    id: 77,
    value: "KRW",
    name: "KRW",
    title: "South Korean won",
    symbol: "₩",
    label: "₩",
  },
  {
    id: 78,
    value: "KWD",
    name: "KWD",
    title: "Kuwaiti dinar",
    symbol: "د.ك",
    label: "د.ك",
  },
  {
    id: 79,
    value: "KYD",
    name: "KYD",
    title: "Cayman Islands dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 80,
    value: "KZT",
    name: "KZT",
    title: "Kazakhstani tenge",
    symbol: "₸",
    label: "₸",
  },
  {
    id: 81,
    value: "LAK",
    name: "LAK",
    title: "Lao kip",
    symbol: "₭",
    label: "₭",
  },
  {
    id: 82,
    value: "LBP",
    name: "LBP",
    title: "Lebanese pound",
    symbol: "ل.ل",
    label: "ل.ل",
  },
  {
    id: 83,
    value: "LKR",
    name: "LKR",
    title: "Sri Lankan rupee",
    symbol: "Rs",
    label: "Rs",
  },
  {
    id: 84,
    value: "LRD",
    name: "LRD",
    title: "Liberian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 85,
    value: "LSL",
    name: "LSL",
    title: "Lesotho loti",
    symbol: "L",
    label: "L",
  },
  {
    id: 86,
    value: "LYD",
    name: "LYD",
    title: "Libyan dinar",
    symbol: "ل.د",
    label: "ل.د",
  },
  {
    id: 87,
    value: "MAD",
    name: "MAD",
    title: "Moroccan dirham",
    symbol: "د.م.",
    label: "د.م.",
  },
  {
    id: 88,
    value: "MDL",
    name: "MDL",
    title: "Moldovan leu",
    symbol: "L",
    label: "L",
  },
  {
    id: 89,
    value: "MGA",
    name: "MGA",
    title: "Malagasy ariary",
    symbol: "Ar",
    label: "Ar",
  },
  {
    id: 90,
    value: "MKD",
    name: "MKD",
    title: "Macedonian denar",
    symbol: "ден",
    label: "ден",
  },
  {
    id: 91,
    value: "MMK",
    name: "MMK",
    title: "Burmese kyat",
    symbol: "Ks",
    label: "Ks",
  },
  {
    id: 92,
    value: "MNT",
    name: "MNT",
    title: "Mongolian tögrög",
    symbol: "₮",
    label: "₮",
  },
  {
    id: 93,
    value: "MOP",
    name: "MOP",
    title: "Macanese pataca",
    symbol: "P",
    label: "P",
  },
  {
    id: 94,
    value: "MRU",
    name: "MRU",
    title: "Mauritanian ouguiya",
    symbol: "UM",
    label: "UM",
  },
  {
    id: 95,
    value: "MUR",
    name: "MUR",
    title: "Mauritian rupee",
    symbol: "₨",
    label: "₨",
  },
  {
    id: 96,
    value: "MVR",
    name: "MVR",
    title: "Maldivian rufiyaa",
    symbol: "Rf",
    label: "Rf",
  },
  {
    id: 97,
    value: "MWK",
    name: "MWK",
    title: "Malawian kwacha",
    symbol: "MK",
    label: "MK",
  },
  {
    id: 98,
    value: "MXN",
    name: "MXN",
    title: "Mexican peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 99,
    value: "MYR",
    name: "MYR",
    title: "Malaysian ringgit",
    symbol: "RM",
    label: "RM",
  },
  {
    id: 100,
    value: "MZN",
    name: "MZN",
    title: "Mozambican metical",
    symbol: "MT",
    label: "MT",
  },
  {
    id: 101,
    value: "NAD",
    name: "NAD",
    title: "Namibian dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 102,
    value: "NGN",
    name: "NGN",
    title: "Nigerian naira",
    symbol: "₦",
    label: "₦",
  },
  {
    id: 103,
    value: "NIO",
    name: "NIO",
    title: "Nicaraguan córdoba",
    symbol: "C$",
    label: "C$",
  },
  {
    id: 104,
    value: "NOK",
    name: "NOK",
    title: "Norwegian krone",
    symbol: "kr",
    label: "kr",
  },
  {
    id: 105,
    value: "NPR",
    name: "NPR",
    title: "Nepalese rupee",
    symbol: "₨",
    label: "₨",
  },
  {
    id: 106,
    value: "NZD",
    name: "NZD",
    title: "New Zealand dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 107,
    value: "OMR",
    name: "OMR",
    title: "Omani rial",
    symbol: "ر.ع.",
    label: "ر.ع.",
  },
  {
    id: 108,
    value: "PAB",
    name: "PAB",
    title: "Panamanian balboa",
    symbol: "B/.",
    label: "B/.",
  },
  {
    id: 109,
    value: "PEN",
    name: "PEN",
    title: "Peruvian sol",
    symbol: "S/.",
    label: "S/.",
  },
  {
    id: 110,
    value: "PGK",
    name: "PGK",
    title: "Papua New Guinean kina",
    symbol: "K",
    label: "K",
  },
  {
    id: 111,
    value: "PHP",
    name: "PHP",
    title: "Philippine peso",
    symbol: "₱",
    label: "₱",
  },
  {
    id: 112,
    value: "PKR",
    name: "PKR",
    title: "Pakistani rupee",
    symbol: "₨",
    label: "₨",
  },
  {
    id: 113,
    value: "PLN",
    name: "PLN",
    title: "Polish złoty",
    symbol: "zł",
    label: "zł",
  },
  {
    id: 114,
    value: "PYG",
    name: "PYG",
    title: "Paraguayan guaraní",
    symbol: "₲",
    label: "₲",
  },
  {
    id: 115,
    value: "QAR",
    name: "QAR",
    title: "Qatari riyal",
    symbol: "ر.ق",
    label: "ر.ق",
  },
  {
    id: 116,
    value: "RON",
    name: "RON",
    title: "Romanian leu",
    symbol: "lei",
    label: "lei",
  },
  {
    id: 117,
    value: "RSD",
    name: "RSD",
    title: "Serbian dinar",
    symbol: "дин.",
    label: "дин.",
  },
  {
    id: 118,
    value: "RUB",
    name: "RUB",
    title: "Russian ruble",
    symbol: "₽",
    label: "₽",
  },
  {
    id: 119,
    value: "RWF",
    name: "RWF",
    title: "Rwandan franc",
    symbol: "FRw",
    label: "FRw",
  },
  {
    id: 120,
    value: "SAR",
    name: "SAR",
    title: "Saudi riyal",
    symbol: "ر.س",
    label: "ر.س",
  },
  {
    id: 121,
    value: "SBD",
    name: "SBD",
    title: "Solomon Islands dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 122,
    value: "SCR",
    name: "SCR",
    title: "Seychelles rupee",
    symbol: "₨",
    label: "₨",
  },
  {
    id: 123,
    value: "SDG",
    name: "SDG",
    title: "Sudanese pound",
    symbol: "ج.س.",
    label: "ج.س.",
  },
  {
    id: 124,
    value: "SEK",
    name: "SEK",
    title: "Swedish krona",
    symbol: "kr",
    label: "kr",
  },
  {
    id: 125,
    value: "SGD",
    name: "SGD",
    title: "Singapore dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 126,
    value: "SHP",
    name: "SHP",
    title: "Saint Helena pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 127,
    value: "SLL",
    name: "SLL",
    title: "Sierra Leonean leone",
    symbol: "Le",
    label: "Le",
  },
  {
    id: 128,
    value: "SOS",
    name: "SOS",
    title: "Somali shilling",
    symbol: "Sh",
    label: "Sh",
  },
  {
    id: 129,
    value: "SRD",
    name: "SRD",
    title: "Surinamese dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 130,
    value: "SSP",
    name: "SSP",
    title: "South Sudanese pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 131,
    value: "STN",
    name: "STN",
    title: "São Tomé and Príncipe dobra",
    symbol: "Db",
    label: "Db",
  },
  {
    id: 132,
    value: "SYP",
    name: "SYP",
    title: "Syrian pound",
    symbol: "£",
    label: "£",
  },
  {
    id: 133,
    value: "SZL",
    name: "SZL",
    title: "Eswatini lilangeni",
    symbol: "L",
    label: "L",
  },
  {
    id: 134,
    value: "THB",
    name: "THB",
    title: "Thai baht",
    symbol: "฿",
    label: "฿",
  },
  {
    id: 135,
    value: "TJS",
    name: "TJS",
    title: "Tajikistani somoni",
    symbol: "ЅМ",
    label: "ЅМ",
  },
  {
    id: 136,
    value: "TMT",
    name: "TMT",
    title: "Turkmenistani manat",
    symbol: "m",
    label: "m",
  },
  {
    id: 137,
    value: "TND",
    name: "TND",
    title: "Tunisian dinar",
    symbol: "د.ت",
    label: "د.ت",
  },
  {
    id: 138,
    value: "TOP",
    name: "TOP",
    title: "Tongan paʻanga",
    symbol: "T$",
    label: "T$",
  },
  {
    id: 139,
    value: "TRY",
    name: "TRY",
    title: "Turkish lira",
    symbol: "₺",
    label: "₺",
  },
  {
    id: 140,
    value: "TTD",
    name: "TTD",
    title: "Trinidad and Tobago dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 141,
    value: "TVD",
    name: "TVD",
    title: "Tuvaluan dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 142,
    value: "TWD",
    name: "TWD",
    title: "New Taiwan dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 143,
    value: "TZS",
    name: "TZS",
    title: "Tanzanian shilling",
    symbol: "Sh",
    label: "Sh",
  },
  {
    id: 144,
    value: "UAH",
    name: "UAH",
    title: "Ukrainian hryvnia",
    symbol: "₴",
    label: "₴",
  },
  {
    id: 145,
    value: "UGX",
    name: "UGX",
    title: "Ugandan shilling",
    symbol: "Sh",
    label: "Sh",
  },
  {
    id: 146,
    value: "USD",
    name: "USD",
    title: "United States dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 147,
    value: "UYU",
    name: "UYU",
    title: "Uruguayan peso",
    symbol: "$",
    label: "$",
  },
  {
    id: 148,
    value: "UZS",
    name: "UZS",
    title: "Uzbekistani soʻm",
    symbol: "soʻm",
    label: "soʻm",
  },
  {
    id: 149,
    value: "VES",
    name: "VES",
    title: "Venezuelan bolívar soberano",
    symbol: "Bs.",
    label: "Bs.",
  },
  {
    id: 150,
    value: "VND",
    name: "VND",
    title: "Vietnamese đồng",
    symbol: "₫",
    label: "₫",
  },
  {
    id: 151,
    value: "VUV",
    name: "VUV",
    title: "Vanuatu vatu",
    symbol: "VT",
    label: "VT",
  },
  {
    id: 152,
    value: "WST",
    name: "WST",
    title: "Samoan tālā",
    symbol: "T",
    label: "T",
  },
  {
    id: 153,
    value: "XAF",
    name: "XAF",
    title: "Central African CFA franc",
    symbol: "Fr",
    label: "Fr",
  },
  {
    id: 154,
    value: "XCD",
    name: "XCD",
    title: "East Caribbean dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 155,
    value: "XDR",
    name: "XDR",
    title: "Special drawing rights",
    symbol: "SDR",
    label: "SDR",
  },
  {
    id: 156,
    value: "XOF",
    name: "XOF",
    title: "West African CFA franc",
    symbol: "Fr",
    label: "Fr",
  },
  {
    id: 157,
    value: "XPF",
    name: "XPF",
    title: "CFP franc",
    symbol: "Fr",
    label: "Fr",
  },
  {
    id: 158,
    value: "YER",
    name: "YER",
    title: "Yemeni rial",
    symbol: "﷼",
    label: "﷼",
  },
  {
    id: 159,
    value: "ZAR",
    name: "ZAR",
    title: "South African rand",
    symbol: "R",
    label: "R",
  },
  {
    id: 160,
    value: "ZMW",
    name: "ZMW",
    title: "Zambian kwacha",
    symbol: "ZK",
    label: "ZK",
  },
  {
    id: 161,
    value: "ZWL",
    name: "ZWL",
    title: "Zimbabwean dollar",
    symbol: "$",
    label: "$",
  },
  {
    id: 162,
    value: "GBP",
    name: "GBP",
    title: "British pound",
    symbol: "£",
    label: "£",
  },
];
